image: appirio/dx-java:latest

stages:
  - build
  - quality_scan
  - deploy
  - rollback

variables:
  JAR_LOCATION: "sonar-apex-plugin/target/*.jar"
  CODE_COVERAGE: "coverage"

.build_jar:
  stage: build
  script:
    - mvn package -Dbuild.number=$CI_PIPELINE_ID
  cache:
    key: $CI_PIPELINE_ID
    paths:
    - apex-checks/target/
    - apex-squid/target/
    - apex-toolkit/target/
    - sonar-apex-plugin/target/
  artifacts:
    name: "CI_COMMIT_REF_NAME/$CI_JOB_ID"
    paths:
      - $JAR_LOCATION
    when: on_success
    expire_in: 1 week

.sonarqube_publish:
  stage: quality_scan
  script:
    - ls apex-checks/target
    - ls $CI_PROJECT_DIR/apex-checks
    - sonar-scanner
      -Dsonar.host.url=https://sonar.appirio.com
      -Dsonar.login=$SONAR_LOGIN
      -Dsonar.projectKey=$CI_PROJECT_PATH_SLUG
      -Dsonar.links.scm=$CI_PROJECT_URL
      -Dsonar.projectVersion=$CI_PIPELINE_ID
      -Dsonar.java.binaries=$CI_PROJECT_DIR/apex-checks/target/,$CI_PROJECT_DIR/apex-squid/target/,$CI_PROJECT_DIR/apex-toolkit/target/,$CI_PROJECT_DIR/sonar-apex-plugin/target/
      -Dsonar.junit.reportPaths=$CI_PROJECT_DIR/apex-checks/target/surefire-reports,$CI_PROJECT_DIR/apex-squid/target/surefire-reports,$CI_PROJECT_DIR/sonar-apex-plugin/target/surefire-reports
      -Dsonar.jacoco.reportPaths=$CI_PROJECT_DIR/apex-checks/target/jacoco.exec,$CI_PROJECT_DIR/apex-squid/target/jacoco.exec,$CI_PROJECT_DIR/sonar-apex-plugin/target/jacoco.exec
      -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME
      -Dsonar.gitlab.max_blocker_issues_gate=5
      -Dsonar.gitlab.max_critical_issues_gate=5
  cache:
    key: $CI_PIPELINE_ID
    paths:
    - apex-checks/target/
    - apex-squid/target/
    - apex-toolkit/target/
    - sonar-apex-plugin/target/

deploy:
  stage: deploy
  when: manual
  script:
    - echo "$HOST_KEY" >> known_hosts
    - echo "$SONAR_SERVER_KEY" > sonar.key
    - chmod 600 sonar.key
    - echo "Backing up the existing plugin"
    - scp -i sonar.key -o "UserKnownHostsFile known_hosts" $SONAR_SERVER_USER@$SONAR_SERVER_IP:sonar-plugins/apex-plugin.jar apex-plugin-backup.jar
  artifacts:
    name: $CI_PIPELINE_ID/backup
    paths:
      - apex-plugin-backup.jar
    when: on_success
    expire_in: 1 week
  cache:
    key: $CI_PIPELINE_ID
    paths:
      - apex-plugin-backup.jar

restore_plugin_from_backup:
  stage: rollback
  when: manual
  script:
    - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
    - npm publish
  cache:
    key: $CI_PIPELINE_ID
    paths:
      - apex-plugin-backup.jar

.build_folders: &cache_builds
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
    - apex-checks/target/
    - apex-squid/target/
    - apex-toolkit/target/
    - sonar-apex-plugin/target/
